title: wtfsystems.net
description: >-
  Personal website of Matthew Evans
url: "https://www.wtfsystems.net"
github_username:  wtfsystems

lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
sass:
  style: compressed
include: [docs]